### ISSUE TITLE
[REQUEST] Add Docker Support

### ISSUE THREAD

**Issue by ad3n** [symfony/symfony-demo#476] opened 2017-02-17 04:23 UTC
Add Docker support

**Comment by bocharsky-bw** [comment] 2017-02-17 07:34
@ad3n The title is not so obvious. Could you change it?

Something related to #79

**Comment by ad3n** [comment] 2017-02-17 08:07
@bocharsky-bw : sorry i'm too fast :-D

**Comment by javiereguiluz** [comment] 2017-02-17 08:55
@ad3n the problem is that we tried to do that in the past (#79) but we had to abandon the idea because people couldn't agree on what to do. I don't use Docker, so I don't know if the situation has improved in the past months. Could we provide a good Docker support that most people can agree on? Thanks!

**Comment by javiereguiluz** [comment] 2017-07-27 07:50
Docker always excites developers ... but for some reason, we never get anything done about it. I'm planning to upgrade the Symfony Demo app to Flex VERY SOON. So I prefer to close this issue as "won't fix for now" and wait to see what great things will @dunglas prepare for Docker + Symfony Flex (see https://github.com/symfony/flex/pull/128) Thanks!

**Closed by javiereguiluz** 2017-07-27 07:50 UTC
Labels: Feature
