### ISSUE TITLE
Platform tied to 5.3.9 prevents installation of recent packages

### ISSUE THREAD

**Issue by andig** [symfony/symfony-demo#343] opened 2016-06-03 09:09 UTC
I'm new to Symfony so I'm not sure if I'm using composer in the expected way, but on php 5.6 I cannot install modules that require php >5.5:

	>composer require peehaa/opcachegui:^1.0
	./composer.json has been updated
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - Installation request for peehaa/opcachegui 1.0 -> satisfiable by peehaa/opcachegui[v1.0.0].
	    - peehaa/opcachegui v1.0.0 requires php >=5.5 -> your PHP version (5.6.7) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.

Reason is in composer.json:

	"config": {
		"bin-dir": "bin",
		"platform": {
		    "php": "5.3.9"
		}
	},

is this needed?

**Comment by stof** [comment] 2016-06-03 09:57
the goal is to be sure that the demo project can be run on any PHP version supported by Symfony, to avoid WTF from users trying the demo with an old PHP version.

If you fork it and modify it for your need, you can change the target PHP version in your composer.json.

**Comment by andig** [comment] 2016-06-03 10:29
> the goal is to be sure that the demo project can be run on any PHP version supported by Symfony

Isn't that already ensured by `require php>=5.3.9`? `config.platform.php` breaks composer installs so you are forced to change it (which is possible of course). Took me some 30 minutes to figure out what was even going one as I haven't seen this composer feature used before.

**Comment by javiereguiluz** [comment] 2016-06-03 10:34
@andig the problem is that:

1. We build the Symfony Demo package in a computer which has PHP 5.5+
2. To build the package, we execute a `composer update`
3. The `require php>=5.3.9` means: "if you computer has at least PHP 5.3.9, then install the highest packages that you can ... e.g. for PHP 5.5"
4. The `config.platform.php = 5.3.9` means: "I don't care what PHP version does this computer use. Update dependencies so they can work in a computer with PHP 5.3.9"

**Comment by voronkovich** [comment] 2016-06-03 10:58
@andig more details about the problem you can find here https://github.com/symfony/symfony-standard/issues/858

**Comment by Pierstoval** [comment] 2016-06-03 13:53
:+1: for @javiereguiluz and @stof , I think we should keep the `config.platform` parameter to the lowest supported PHP version on each project that has to be built as a zipball or any "download&play" thing.
Removing it is _your_ role, as well as reading [Composer's documentation](https://getcomposer.org/doc/06-config.md#platform)

**Comment by voronkovich** [comment] 2016-06-03 14:08
Also you can use the `--ignore-platform-reqs` option to ignore the `config.platform` value.

**Comment by andig** [comment] 2016-06-03 14:43
> Removing it is your role, as well as reading Composer's documentation

I understand the workarounds. You got me on the docs but thats why I've started with the demo. I still couldn't figure out why requiring the php version isn't sufficient. Any hints?

**Comment by andig** [comment] 2016-06-04 08:32
@javiereguiluz so the reason for this setting is ensuring you get a build packagethat will run on 5.3.9? If thats the case then why not strip the config setting after build completes? That way it will contain compatible packages only and leave the door open for newer stuff?

**Comment by xabbuh** [comment] 2016-06-04 13:05
It makes sense to do that in the installer for the demo too. We already do that for regular installations.

**Comment by javiereguiluz** [comment] 2016-06-05 11:33
@xabbuh you are right! I've opened https://github.com/symfony/symfony-installer/issues/255 to implement this idea. Therefore, I'm closing this issue as "can't fix here ... but it will be fixed in the installer".

**Closed by javiereguiluz** 2016-06-05 11:33 UTC
